Задание второго спринта
Nyaksik/BeautyWorld pull request #2
Opened 2021-11-26 07:38 UTC by Nyaksik

- не уверен, как стоило вставить иконку "бургер-меню" - вставил картинкой.

2021-12-06 07:47 UTC, studenttsu requested changes
Общие рекомендации:
- пользоваться возможностями препроцессора
- по возможности более проще описывать классы для элементов
- ещё раз ознакомиться с БЭМ методологией

2021-12-06 07:47 UTC, studenttsu commented on src/index.html
> +                    <div class="burger-menu" style="background-image: url('./assets/img/hamburger.png');"></div>
Лучше сделать тегом кнопки и фоновое изображение можно убрать в файл стилей, ведь это статичная картинка и мы её скорее всего менять не будем

2021-12-06 07:47 UTC, studenttsu commented on src/index.html
> +                    <div class="burger-menu" style="background-image: url('./assets/img/hamburger.png');"></div>
Вот разные идеи как ещё можно реализовать
https://codepen.io/search/pens?q=hamburger

2021-12-06 07:47 UTC, studenttsu commented on src/index.html
> +                        <div class="service services-prices__service col-md-5 col-8">
Похоже на усложнение. Не совсем понял для чего отдельный класс `description-service`?
`services-prices__service` не нашёл, где используется в стилях.

Можно проще - так код чище

```html
<div class="service col-md-5 col-8">
    <div class="service__description">
        <h5 class="service__name">Женская стрижка</h5>
        <p class="service__descr">Короткие волосы</p>
    </div>
    <p class="service__price">1200</p>
</div>
```

2021-12-06 07:47 UTC, studenttsu commented on src/index.html
> +                                <h4 class="master__name popular-service__title">Краснова Ирина</h4>
`нужно поправить`

`popular-service__title`, `popular-service__subtitle` не принадлежать `master`

https://ru.bem.info/methodology/quick-start/#%D0%BF%D1%80%D0%B8%D0%BD%D0%B0%D0%B4%D0%BB%D0%B5%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C

2021-12-06 07:47 UTC, studenttsu commented on src/style/header.scss
> +    .hero__title {
Стоит пользоваться вложенностью и объединить смежные классы под одной "крышей", ведь это преимущество препроцессора на css. Код будет проще поддерживать. Это стоит пройтись по всем стилям и "причесать" их

```
.hero {
    &__title {
        ...
    }

    ...
}

```

2021-12-06 07:47 UTC, studenttsu commented on src/index.html
> +                <section class="masters">
Предлагаю сделать более универсальную разметку для секций. Далее стили писать только для содержимого секции

```html
<section class="section">
<!-- Может быть модификатор section_gray для секции с фоном. 
Модификаторы в основном применяются именно к базовой реализации блока -->
        <div class="container">
            <header class="section__header">
                <h2 class="section__title">Заголовок</h2>
                <div class="section__tools">Кнопки</div><!-- Может отсутствовать -->
            </header>

            <div class="section__inner">
                Содержимое секции
            </div>
        </div>
    </section>
```

2021-12-08 08:56 UTC, Nyaksik commented
Большую часть исправил, но такое ощущение, что поудалял лишнего.

2021-12-24 06:57 UTC, merged