Sprint3
Nyaksik/BeautyWorld pull request #3
Opened 2021-11-29 06:37 UTC by Nyaksik

2021-11-29 06:58 UTC, Nyaksik commented
- Пока не получается задеплоить. В логах написано, что такой команды нет, но она есть и в VSC она отрабатывает.
![image](https://user-images.githubusercontent.com/82147390/143822083-9aa91fdd-f4b5-48eb-acfe-6c8df3965a05.png)
![image](https://user-images.githubusercontent.com/82147390/143822106-fdf5fd92-d877-4c25-a1e2-25c1eafaadae.png)

2021-11-29 07:05 UTC, Nyaksik commented
Как я понял, задеплоить я не смогу, пока не замёржу эту ветку с основной. Верно?

2021-12-06 08:06 UTC, studenttsu requested changes
Обрати внимание на "переполнение" контентом, чтобы ничего не ломалось при вставке большого количества контента и разных картинок. Ведь в рабочем сайте могут быть какие угодно данные

2021-12-06 08:06 UTC, studenttsu commented on src/style/main.scss
> +        .advantage {
Зачем тут advantage вложен именно таким образом в advantages? На выходе будет:

```css
.advantages .advantage,
.advantages .advantages__img
и тд
```

Это повышает специфичность селектора 
https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D1%87%D0%BD%D0%BE%D1%81%D1%82%D1%8C_2
https://developer.mozilla.org/ru/docs/Web/CSS/Specificity

2021-12-08 10:17 UTC, Nyaksik commented
Основное исправил. Рефакторинг проведу, как замёржу ветку sprint2.

2021-12-24 07:12 UTC, merged