Sprint4
Nyaksik/BeautyWorld pull request #4
Opened 2021-12-03 10:25 UTC by Nyaksik

Вроде всё сделал.

Когда прикручивал слайдер к секции "Наши работы" что-то пошло не так и всё пришло переделать. Поэтому там колхоз с псевдоэлементом, но всё работает.

2021-12-03 10:28 UTC, Nyaksik commented
- При деплое плагины отваливаются
![image](https://user-images.githubusercontent.com/82147390/144587559-980c7463-ad1c-4102-921f-8c055bfd37f0.png)
- На локале всё работает
![image](https://user-images.githubusercontent.com/82147390/144587610-ee1426e6-88a0-4adf-ac65-c2e4b3c40b16.png)

2021-12-06 08:18 UTC, studenttsu requested changes
Хорошо получается! 

Request changes - потому что нужно по очереди будет промержить spint2, затем sprint3 и в конце sprint4

2021-12-06 08:18 UTC, studenttsu commented on src/index.html
> +                    <a data-fancybox="video-gallery" data-src="https://youtu.be/dQw4w9WgXcQ">
Почему завернул весь контент в ссылку? Не совсем очевидно, что при клике на текст будет открываться модалка

2021-12-06 08:18 UTC, studenttsu commented on src/js/form.js
> +    btn.addEventListener('click', () => {
Почему обработка не submit события формы?

2021-12-24 07:18 UTC, merged